version: '2'
services:
  mqtt:
    build: .
    image: mqtt
    volumes:
      - mqtt-conf:/mqtt/config:ro
      - mqtt-data:/mqtt/data
      - mqtt-log:/mqtt/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
volumes:
  mqtt-conf:
  mqtt-data:
  mqtt-log:

